### ISSUE TITLE
Fehler (?) gefunden ... 

### ISSUE THREAD

**Issue by NMarkgraf** [luebby/Lehrapps#8]
Heute ist jemand aufgefallen, dass es einen Zuordnungsfehler innerhalb der Darstellungen folgender Shiny App gibt:

https://fomshinyapps.shinyapps.io/Sampling/

 

Die grafischen Aufbereitungen für die Verteilungen des Mittelwerts und der Anteile sind vertauscht. Dies sollte leicht zu korrigieren sein. Könnte aber bei den Studierenden zu Verwirrungen führen.

**Comment by luebby** [comment]
> Stets zu Diensten und umgesetzt. Und: ich fand mich verdammt langsam.
